### ISSUE TITLE
An error message

### ISSUE THREAD

**Issue by UltraFaceguy** [andrepl/JukeLoop#9]
This message occurs when first going near a Jukebox.

2013-06-03 01:06:08 [SEVERE] Exception in thread "Craft Scheduler Thread - 94" 
2013-06-03 01:06:08 [SEVERE] org.apache.commons.lang.UnhandledException: Plugin JukeLoop v0.1.7 generated an exception while executing task 344660
    at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.norcode.bukkit.jukeloop.JukeLoopPlugin$3.run(JukeLoopPlugin.java:308)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:58)
    at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

I doesn't really too much other than barf and look ugly. Everything still works. Still though, I'd like it gone, so I thought I ought to tell you.

**Comment by andrepl** [comment]
Thanks for the report, Fixed in v0.1.8, ,uploading to bukkitdev right now
